Assignment3Client/Assignment3Client/Models/ErrorViewModel.cs
using System;

namespace Assignment3Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment3Client/Assignment3Client/Models/Medication.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3Client.Models
{
    public class Medication
    {
        public int MedicationID { get; set; }
        public string Name { get; set; }
        public string SideEffects { get; set; }
        public int Dosage { get; set; }
        public int MedicationPlan_MedicationPlanID { get; set; }
    }
}

Assignment3Client/Assignment3Client/Models/MedicationPlan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3Client.Models
{
    public class MedicationPlan
    {
        public int MedicationPlanID { get; set; }
        public int Days { get; set; }
        public string Description { get; set; }
        public List<Medication> Medications { get; set; }
    }
}

Assignment3Client/Assignment3Client/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3Client.Models
{
    public class Patient
    {
        public int PatientID { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Address { get; set; }
    }
}

Assignment3Client/Assignment3Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Assignment3Client.Models;
using Grpc.Net.Client;
using GrpcGreeter;

namespace Assignment3Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment3Client/Assignment3Client/Controllers/MedicationPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment3Client.Models;
using Grpc.Net.Client;
using GrpcGreeter;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Assignment3Client.Controllers
{
    public class MedicationPlanController : Controller
    {
        public MedicationPlanController()
        {

        }
        public async Task<IActionResult> Index()
        {
            var channel = GrpcChannel.ForAddress("https://localhost:5001");
            var client = new Greeter.GreeterClient(channel);
            //Here I take the MedicationPlanMessage from the server
            var reply = await client.SayMedicationAsync(new MedicationPlanMessage());
            
            //Create the medication list
            var medications = new List<Medication>();
            foreach(var medication in reply.Medications)
            {
                medications.Add(new Medication
                {
                    MedicationID=medication.MedicationID,
                    Dosage=medication.Dosage,
                    Name=medication.Name,
                    SideEffects=medication.SideEffects
                });
            }

            //Creating the medication plan
            MedicationPlan medicationPlan = new MedicationPlan
            {
                MedicationPlanID = reply.MedicationPlanID,
                Description = reply.Description,
                Days = reply.Days,
                Medications=medications
            };
            ViewBag.Message = medicationPlan;
            return View();
        }
    }
}

Assignment3Client/Assignment3Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Assignment3Client/Assignment3Client/Views/MedicationPlan/Index.cshtml
@using Assignment3Client.Models

@{
    ViewBag.Title = "Index";
}

@{
    var data = ViewBag.Message;
}

<h3>Medicaiton Plan:</h3>
<table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Description </th>
        <th>Days</th>
    </tr>
    <tr>
        <td>@data.MedicationPlanID</td>
        <td>@data.Description</td>
        <td>@data.Days</td>
    </tr>
</table>

<body onload=display_ct();>
    <span id='ct' style="font-size:40px;font-weight:bold;"></span>

</body>

<h3>His Medications:</h3>
<table class="table table-bordered table-hover">
    <tr>
        <th>ID</th>
        <th>Name </th>
        <th>Side Effects</th>
        <th>Dosage</th>
        <th>Taken</th>
    </tr>
    @foreach (var item in data.Medications)
    {
        <tr>
            <td>@item.MedicationID</td>
            <td>@item.Name</td>
            <td>@item.SideEffects</td>
            <td>@item.Dosage</td>
            <td id="output" style="background:red"></td>
            <td><button id="changeGreen" type="button" onclick="alert('Are you sure that you consumed the Medicine?')">Taken</button>
        </tr>
    }
</table>


<script type="text/javascript">
    function display_c() {
        var refresh = 1000; // Refresh rate in milli seconds
        mytime = setTimeout('display_ct()', refresh)
    }

    function display_ct() {
        var x = new Date();
        x.setSeconds = 0;

        var x1 = x.getHours() + ":" + x.getMinutes() + ":" + x.getSeconds();
        document.getElementById('ct').innerHTML = x1;
        display_c();
    }
    
    document.getElementById("changeGreen").onclick = function () {
        document.getElementById("output").style.background = 'green';
    }

</script>

Assignment3Client/Assignment3Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment3Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment3Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicationPlan">Medication Plan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Assignment3Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>